
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm-sample-application
  labels:
    app: ecm-smart-service
spec:
  replicas: 3
  selector:
    matchLabels:
      name: ecm-sample-application
      app: ecm-smart-service
  template:
    metadata:
      name: ecm-sample-application
      labels:
        name: ecm-sample-application
        app: ecm-smart-service

    spec:
      containers:
      - name: ecm-sample-application
        image: narasimhamurthyk/ecm-sample-application
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
